### ISSUE TITLE
Add OAuth flow capabilities

### ISSUE THREAD

**Issue by CalvinScott** [CalvinScott/retsly-swift-sdk#1]
## Team
- @CalvinScott
## Overview

OAuth is one of the bigger blockers for iOS development with the Retsly platform. Gotta figure that out for the people.
## Tasks
- [ ] Think about it
- [ ] Get back to this issue in like a year
## Deployment
- [ ] Push to master because lone repo madness
## Release

These changes are _minor_
